### ISSUE TITLE
Backdrop upgrade status breaks Drupal cron

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/backdrop_upgrade_status#18] opened 2021-04-16 08:13 UTC
Didn't find the time to dig in, but I noticed that when the module in enabled, Drupal cron runs break.

1. Cron via commandline - returns the front page content, no cron success in dblog
2. Cron via UI - redirects to the upgrade status page, no cron success in dblog

Module version: 7.x-1.1

While the module is enabled, there are no successful cron runs in dblog. Disabling the module fixes that.

**Comment by jenlampton** [comment] 2021-04-29 17:26
I think this is a duplicate of https://github.com/backdrop-contrib/backdrop_upgrade_status/issues/16, re-titling that issue to make it clearer.

**Closed as completed by jenlampton** 2021-04-29 17:26 UTC
