### ISSUE TITLE
Include Font Awesome module name change

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/backdrop_upgrade_status#22] opened 2021-11-03 22:45 UTC
I don't see an issue for this, but I can be the first to experience it. 

The new Report is suggesting that I port modules that have already been ported and have stable releases. 

Example: Font Awesome

**Comment by jenlampton** [comment] 2022-09-26 06:01
Well, I tried to reproduce this today, but ran into https://github.com/backdrop-contrib/backdrop_upgrade_status/issues/33. 

I expect your issue with font awesome is because the project's name changed for Backdrop:
* https://backdropcms.org/project/font_awesome
* https://www.drupal.org/project/fontawesome

We can add a special case for this in the update instructions.

**Comment by jenlampton** [comment] 2023-04-13 21:42
This should be fixed by recent commits. Closing now, but please create new issues for other modules that behave this way.

**Closed as completed by jenlampton** 2023-04-13 21:42 UTC
